name: C++ CMake Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up C++ toolchain
      uses: actions/setup-python@v5  # Optional, in case Python needed for tools
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ protobuf-compiler libprotobuf-dev libgrpc++-dev

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --parallel

