# .github/workflows/dependency-update.yml
name: Dependency Updates

on:
  schedule:
    - cron: '0 6 * * MON'  # Weekly on Monday at 6 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libprotobuf-dev \
          libgrpc++-dev \
          protobuf-compiler-grpc \
          protobuf-compiler \
          libhdf5-dev \
          libhdf5-cpp-103 \
          nlohmann-json3-dev \
          libmongoc-dev \
          libmongocxx-dev

    - name: Check for dependency updates
      run: |
        echo "Checking for system package updates..."
        apt list --upgradable 2>/dev/null | grep -E "(protobuf|grpc|hdf5|nlohmann|mongo)" || true
        
        echo "Checking CMake version..."
        cmake --version
        
        echo "Checking compiler versions..."
        gcc --version
        g++ --version

    - name: Test build with current dependencies
      run: |
        chmod +x DataProvider/build_dp.sh
        ./DataProvider/build_dp.sh clean
        ./DataProvider/build_dp.sh

    - name: Create dependency update issue
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Dependency Update Issue Detected',
            body: 'Automated dependency check found potential issues. Please review the workflow run for details.',
            labels: ['dependencies', 'maintenance']
          });
